#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - identity
    - keyboard
    - locale
    - network
    - storage
    - timezone

  ssh:
    install-server: true

  packages:
    - linux-generic
    - wpasupplicant
    - intel-microcode
    - iucode-tool
    - iptables

  late-commands:
    - "curtin in-target --target=/target -- apt update && apt install -y chrony build-essential iw iwd avahi-utils"
    - "mkdir -p /target/usr/src/dappnode"
    - "cp -ar /cdrom/dappnode/* /target/usr/src/dappnode/"
    - "cp -a /cdrom/dappnode/scripts/rc.local /target/etc/rc.local"
    - "chmod +x /target/usr/src/dappnode/scripts/dappnode_install_pre.sh"
    - "touch /target/usr/src/dappnode/.firstboot"
#    - "cp -ar /etc/netplan/* /target/etc/netplan/" # TODO: Is this necessary?
#    - "chmod +x /target/usr/src/dappnode/scripts/static_ip.sh" # TODO: Remove if not necessary to validate IP
#    - "sh -c 'gpasswd -a $(getent passwd 1000 | cut -d: -f1) sudo' " # TODO: Check if dappnode user needs to be manually added to sudoers
#    - "/target/usr/src/dappnode/scripts/static_ip.sh"
    - "/target/usr/src/dappnode/scripts/dappnode_install_pre.sh UPDATE"
