#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
  network:
    network:
      version: 2
      ethernets:
        eth0:
          dhcp4: true
  storage:
    layout:
      name: lvm
      config:
        - {ptable: gpt, path: sda, preserve: false, name: '', grub_device: true}
        - {volume_group: rootvg, devices: [sda1]}
        - {name: root, volgroup: rootvg, size: 100%FREE, format: {type: ext4}, mount: {path: /}}
  identity:
    hostname: dappnode
    username: dappnode
    password: "$6$insecur3$rnEv9Amdjn3ctXxPYOlzj/cwvLT43GjWzkPECIHNqd8Vvza5bMG8QqMwEIBKYqnj609D.4ngi4qlmt29dLE.71"
  ssh:
    install-server: true
    allow-pw: true
    authorized-keys: []
  user-data:
    disable_root: false
  packages:
    - openssh-server
    - vim
    - sudo
#    - build-essential # TODO: FIX
    - linux-generic
#    - iw # TODO: FIX
#    - iwd
    - wpasupplicant
    - intel-microcode
    - iucode-tool
#    - firmware-misc-nonfree # TODO: Remove?
#    - firmware-iwlwifi # TODO: Remove?
#    - avahi-utils # TODO: Fix
#    - iptables # TODO: Try
  timezone: UTC
  ntp:
    enabled: true
  late-commands:
    - "mkdir -p /target/usr/src/dappnode"
    - "cp -ar /cdrom/dappnode/* /target/usr/src/dappnode/"
    - "cp -a /cdrom/dappnode/scripts/rc.local /target/etc/rc.local"
    - "chmod +x /target/usr/src/dappnode/scripts/dappnode_install_pre.sh"
    - "echo 'touch /usr/src/dappnode/.firstboot' | in-target"
#    - "in-target /usr/src/dappnode/scripts/dappnode_install_pre.sh UPDATE" # TODO: Fix
